Repository OpenCPN/OpenCPN, pull requests merged in 2018-02, with the labels that each got.

#991 Switch Windows build to VS2017 and wxWidgets 3.1.1
  CMakeLists.txt
  VERSION.cmake
  appveyor.yml
  buildwin/crashrpt/CrashRpt1402.lib
  buildwin/crashrpt/CrashRpt1403.dll
  buildwin/crashrpt/CrashRpt1403.lib
  buildwin/crashrpt/CrashSender1403.exe
  buildwin/libcurl.lib
  include/datastream.h
  plugins/grib_pi/CMakeLists.txt
  plugins/grib_pi/src/zlib-1.2.3/zconf.h
  plugins/grib_pi/src/zlib-1.2.3/zlib.h
Labels: enhancement, needs testing

#987 Fix several sizer related asserts
  include/options.h
  src/AISTargetQueryDialog.cpp
  src/TrackPropDlg.cpp
  src/about.cpp
  src/chart1.cpp
  src/options.cpp
  src/routemanagerdialog.cpp
  src/routeprop.cpp
Labels: bug

#994 Wx311 updates
  plugins/dashboard_pi/src/dashboard_pi.cpp
  plugins/dashboard_pi/src/dashboard_pi.h
  plugins/dashboard_pi/src/gps.cpp
  plugins/dashboard_pi/src/instrument.cpp
  plugins/dashboard_pi/src/wind.cpp
  plugins/dashboard_pi/src/wind_history.cpp
  plugins/grib_pi/src/GribUIDialogBase.cpp
  plugins/wmm_pi/src/WmmUIDialog.cpp
  src/AISTargetAlertDialog.cpp
  src/TTYWindow.cpp
  src/cm93.cpp
  src/compass.cpp
  src/compasswin.cpp
  src/options.cpp
  src/routeprop.cpp
  src/toolbar.cpp
  src/wxcurl/dialog.cpp
Labels: bug

#995 correct route and track messages so they can actually be used by plugins
  src/chart1.cpp
Labels: bug

#988 Grib not def values
  plugins/grib_pi/src/CustomGrid.cpp
  plugins/grib_pi/src/GribRecord.cpp
Labels: bug

#985 Assign a unique GUID to GPX loaded as a layer
  src/NavObjectCollection.cpp
  src/routeman.cpp
Labels: bug

#990 Coverity cleanup
  include/glChartCanvas.h
  src/AIS_Decoder.cpp
  src/NavObjectCollection.cpp
  src/Osenc.cpp
  src/chart1.cpp
  src/chartdb.cpp
  src/chartimg.cpp
  src/chcanv.cpp
  src/glChartCanvas.cpp
  src/options.cpp
  src/routeman.cpp
  src/viewport.cpp
Labels: bug

#993 FS#2094 - True Wind Dir. & Speed does not indicate above 199 degrees TWD
  plugins/dashboard_pi/src/dashboard_pi.cpp
Labels: bug

#1003 Fix portable save of CHRTLIST.DAT and MMSINAME.CSV
  src/OCPNPlatform.cpp
  src/chart1.cpp
Labels: bug

#1007 Implement C++11 for all platforms.
  .travis.yml
  CMakeLists.txt
  include/printtable.h
  include/routeprintout.h
  include/trackprintout.h
  plugins/wmm_pi/src/MagneticPlotMap.cpp
Labels: enhancement

#1010 Add appdata metafile - gnome-software support.
  CMakeLists.txt
  data/opencpn.appdata.xml
  src/bitmaps/opencpn-64.png
Labels: enhancement
