Repository OpenCPN/OpenCPN, pull requests merged in 2018-06, with the labels that each got.

#999 GetVPRegionIntersect on error only delete points array if it was allo…
  src/viewport.cpp
Labels: bug

#1000 don't fail if grib overlay size start small
  plugins/grib_pi/src/GribOverlayFactory.cpp
Labels: bug

#1012 Correct and clean up portable file savings
  include/OCPNPlatform.h
  src/OCPNPlatform.cpp
  src/chart1.cpp
  src/navutil.cpp
  src/options.cpp
Labels: bug, enhancement

#1061 Fix internationalism for zoom level pop-ups
  po/POTFILES.in
  src/DetailSlider.cpp
Labels: bug

#1075 Fix land crossing test for perfectly vertical line segments
  src/gshhs.cpp
Labels: bug

#1078 s52plib factorization and memory leak
  include/s52plib.h
  src/s52plib.cpp
Labels: bug

#1058 chart1.cpp: Fix get_X11_property
  src/chart1.cpp
Labels: bug

#1045 Chartbase thinko
  include/chartimg.h
  src/glTexCache.cpp
Labels: bug

#1080 Implement optional dark window decorations on macOS
  CMakeLists.txt
  include/options.h
  src/DarkMode.h
  src/DarkMode.mm
  src/chart1.cpp
  src/chcanv.cpp
  src/navutil.cpp
  src/options.cpp
Labels: enhancement, macOS

#1082 Correct somme mal-function related with touch mode and draghandle
  src/chcanv.cpp
Labels: bug

#1063 Optimize history graphs by avoiding thousands of calls to OS TZ func
  plugins/dashboard_pi/src/baro_history.cpp
  plugins/dashboard_pi/src/baro_history.h
  plugins/dashboard_pi/src/wind_history.cpp
  plugins/dashboard_pi/src/wind_history.h
Labels: enhancement

#1064 add free predictwind EMCWF grib
  plugins/grib_pi/src/GribV1Record.cpp
Labels: enhancement

#1052 Implement filtering in the route and waypoint manager
  include/Layer.h
  include/Route.h
  include/Track.h
  include/routemanagerdialog.h
  src/AISTargetQueryDialog.cpp
  src/AIS_Decoder.cpp
  src/NavObjectCollection.cpp
  src/Track.cpp
  src/TrackPropDlg.cpp
  src/chart1.cpp
  src/chcanv.cpp
  src/kml.cpp
  src/navutil.cpp
  src/pluginmanager.cpp
  src/routemanagerdialog.cpp
  src/trackprintout.cpp
Labels: enhancement

#1077 Add depth offset feature to Dashboard
  plugins/dashboard_pi/src/dashboard_pi.cpp
  plugins/dashboard_pi/src/dashboard_pi.h
Labels: enhancement

#1060 Unit test 2
  include/chart1.h
  src/chart1.cpp
  src/chcanv.cpp
Labels: enhancement
