Repository OpenCPN/OpenCPN, pull requests merged in 2019-02, with the labels that each got.

#1244 Correct selecting waypoints at < scamin
  include/RoutePoint.h
  src/RoutePoint.cpp
  src/Select.cpp
Labels: bug

#1257 AIS country code. One name change and clean up
  src/AIS_Target_Data.cpp
Labels: enhancement

#1258 Remove a tiny amount unused globals, includes etc
  src/AIS_Bitstring.cpp
  src/ConfigMgr.cpp
  src/OCPN_Sound.cpp
  src/ais.cpp
  src/androidUTIL.cpp
  src/chcanv.cpp
  src/cm93.cpp
  src/options.cpp
  src/pluginmanager.cpp
  src/s57chart.cpp
  src/s57mgr.cpp
Labels: enhancement

#1270 Enhance the layer WPT visibility logic
  include/Layer.h
  include/NavObjectCollection.h
  include/RoutePoint.h
  include/routemanagerdialog.h
  plugins/wmm_pi/po/wmm_pi.pot
  src/Layer.cpp
  src/NavObjectCollection.cpp
  src/navutil.cpp
  src/routemanagerdialog.cpp
Labels: enhancement

#1274 Implement switchable SOG/VMG for TTG calculation in console window
  include/concanv.h
  src/concanv.cpp
Labels: done, enhancement

#1273 RMB should send VMG not SOG
  src/routeman.cpp
Labels: bug

#1262 Memory leak and deleting open files
  include/Osenc.h
  plugins/grib_pi/src/GribRequestDialog.cpp
  plugins/grib_pi/src/GribUIDialog.cpp
  plugins/grib_pi/src/grib_pi.cpp
  plugins/grib_pi/src/grib_pi.h
  src/ChartDataInputStream.cpp
  src/OCPNPlatform.cpp
  src/Osenc.cpp
  src/Quilt.cpp
Labels: bug

#1264 FontMgr: Avoid incorrect types and superfluous casts
  src/FontMgr.cpp
Labels: bug, enhancement

#1271 Make CPN_GLCaps a class, fixes segfault
  include/glChartCanvas.h
  src/OCPNPlatform.cpp
Labels: bug

#1275 Enhancements to the AIS and DSC handling as requested by SAR services
  src/AIS_Decoder.cpp
  src/AIS_Target_Data.cpp
  src/ConfigMgr.cpp
  src/chart1.cpp
  src/navutil.cpp
Labels: done, enhancement
