Repository OpenCPN/OpenCPN, pull requests merged in 2019-03, with the labels that each got.

#1281 Many window modality and color related changes
  include/AISTargetQueryDialog.h
  include/DetailSlider.h
  include/MUIBar.h
  include/S57QueryDialog.h
  include/SendToGpsDlg.h
  include/TCWin.h
  include/chart1.h
  include/concanv.h
  include/options.h
  include/toolbar.h
  plugins/chartdldr_pi/src/chartdldr_pi.cpp
  plugins/chartdldr_pi/src/chartdldr_pi.h
  src/AISTargetAlertDialog.cpp
  src/AISTargetQueryDialog.cpp
  src/CanvasOptions.cpp
  src/ChInfoWin.cpp
  src/ConnectionParams.cpp
  src/DetailSlider.cpp
  src/GoToPositionDialog.cpp
  src/LinkPropDlg.cpp
  src/MUIBar.cpp
  src/RoutePropDlgImpl.cpp
  src/S57QueryDialog.cpp
  src/TCWin.cpp
  src/TrackPropDlg.cpp
  src/chart1.cpp
  src/chcanv.cpp
  src/concanv.cpp
  src/options.cpp
  src/pluginmanager.cpp
  src/toolbar.cpp
Labels: bug, done, enhancement, needs testing

#1285 Fix platform defines
  src/OCPNPlatform.cpp
  src/RoutePropDlgImpl.cpp
  src/canvasMenu.cpp
  src/chart1.cpp
  src/chcanv.cpp
  src/options.cpp
Labels: bug

#1278 Use wxWebView for help display
  .travis.yml
  CMakeLists.txt
  include/AboutFrame.h
  include/AboutFrameImpl.h
  src/AboutFrame.cpp
  src/AboutFrameImpl.cpp
Labels: enhancement

#1299 Travis: enhance the travis build configuration
  .travis.yml
  CMakeLists.txt
  ci/control
  ci/travis-build-debian.sh
  ci/travis-build-osx.sh
  travisci_build.sh
Labels: enhancement

#1305 Avoid crash when creating a route when the first RP finds a nearby one
  src/chcanv.cpp
Labels: bug

#1302 Asan
  src/Select.cpp
  src/chartdb.cpp
  src/toolbar.cpp
Labels: bug

#1306 Allow chart source master catalog update from the internet
  plugins/chartdldr_pi/src/chartdldr_pi.cpp
  plugins/chartdldr_pi/src/chartdldrgui.cpp
  plugins/chartdldr_pi/src/chartdldrgui.h
Labels: enhancement

#1317 Replace the bell sounds with a new popular version
  LICENSING
  data/copyright
  data/sounds/1bells.wav
  data/sounds/2bells.wav
  data/sounds/README.bells
Labels: enhancement

#1318 Small patches
  src/chartdbs.cpp
  src/chartimg.cpp
Labels: bug

#1327 Correct dashboard instruments background colour
  plugins/dashboard_pi/src/instrument.cpp
Labels: bug
